logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 81.70.175.60:27001
        - 81.70.175.60:27002
        - 81.70.175.60:27003
    password: 123456
