logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 81.70.175.60 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: sun
    password: sun20030920
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
